version: "3"

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - back-end/.env
    ports:
      - 4457:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - back-end/.env

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_db
      - node_app
      - app_react

volumes:
  build_react:
  postgres_db: